TIME_INTERVAL_BETWWEN_CLICK_AND_KEYBOARD_CONTOL = 0.1

TIME_INTERVAL_BETWWEN_KEYBOARD_CONTOLS = 0.5

TIME_INTERVAL_BETWWEN_KEYBOARD_CONTOL_AND_TYPING = 0.5

TIME_INTERVAL_BETWWEN_TYPING_AND_ENTER = 0.5

TIME_INTERVAL_BETWWEN_TYPING_AND_ENTER_LONG = 1