TIME_INTERVAL_BETWEEN_CLICK_AND_KEYBOARD_CONTOL = 0.1

TIME_INTERVAL_BETWEEN_KEYBOARD_CONTOLS = 0.5

TIME_INTERVAL_BETWEEN_KEYBOARD_CONTOL_AND_TYPING = 0.5

TIME_INTERVAL_BETWEEN_TYPING_AND_ENTER_LONG = 1