import os

# Image paths
BASE_DIR = "C:\\dev-system\\module-download_automation"
IMAGE_FOLDER = os.path.join('assets', 'image-system')

LOADING_SEARCH_GO = 'loading_search_go.png'
LOADING_EXCEL_GO = 'loading_excel_go.png'
EXCEL_HEADER = 'excel_header.png'
DATA_LENGTH_CAUTION_POPUP = 'data_length_caution_popup.png'
EXCEL_CAUTION_CONFIRM_BUTTON = 'excel_caution_confirm_button.png'
SAVE_CAUTION_POPUP = 'duplicated_name.png'
EXCEL_FOLDER_ARROWS = 'excel_folder_arrows.png'
NO_DATA_POPUP = 'no_data_popup.png'
SAVE_FORMAT_CONFIRM_BUTTON = 'save_format_confirm_button.png'
HEADER_BOS = 'header_bos.png'
HEADER_MOS = 'header_mos.png'
ICON_BOS = 'icon_bos.png'
ICON_MOS = 'icon_mos.png'
HEADER_LOGIN = 'header_login.png'
MOS_EXCEPTION_POPUP = 'mos_exception_popup.png'

IMAGE_PATH_LOADING_SEARCH_GO = os.path.join(IMAGE_FOLDER, LOADING_SEARCH_GO)
IMAGE_PATH_LOADING_EXCEL_GO = os.path.join(IMAGE_FOLDER, LOADING_EXCEL_GO)
IMAGE_PATH_EXCEL_HEADER = os.path.join(IMAGE_FOLDER, EXCEL_HEADER)
IMAGE_PATH_DATA_LENGTH_CAUTION_POPUP = os.path.join(IMAGE_FOLDER, DATA_LENGTH_CAUTION_POPUP)
IMAGE_PATH_EXCEL_CAUTION_CONFIRM_BUTTON = os.path.join(IMAGE_FOLDER, EXCEL_CAUTION_CONFIRM_BUTTON)
IMAGE_PATH_SAVE_CAUTION_POPUP = os.path.join(IMAGE_FOLDER, SAVE_CAUTION_POPUP)
IMAGE_PATH_EXCEL_FOLDER_ARROWS = os.path.join(IMAGE_FOLDER, EXCEL_FOLDER_ARROWS)
IMAGE_PATH_NO_DATA_POPUP = os.path.join(IMAGE_FOLDER, NO_DATA_POPUP)
IMAGE_PATH_SAVE_FORMAT_CONFIRM_BUTTON = os.path.join(IMAGE_FOLDER, SAVE_FORMAT_CONFIRM_BUTTON)
IMAGE_PATH_HEADER_BOS = os.path.join(IMAGE_FOLDER, HEADER_BOS)
IMAGE_PATH_HEADER_MOS = os.path.join(IMAGE_FOLDER, HEADER_MOS)
IMAGE_PATH_ICON_BOS = os.path.join(IMAGE_FOLDER, ICON_BOS)
IMAGE_PATH_ICON_MOS = os.path.join(IMAGE_FOLDER, ICON_MOS)
IMAGE_PATH_HEADER_LOGIN = os.path.join(IMAGE_FOLDER, HEADER_LOGIN)
IMAGE_PATH_MOS_EXCEPTION_POPUP = os.path.join(IMAGE_FOLDER, MOS_EXCEPTION_POPUP)